### ISSUE TITLE
Python Code Review

### ISSUE THREAD

**Issue by AladdinT** [RafikEmad/EmbeddedLinux#1]
### session1 
- 01_Python/01_Introduction/Task1_CountOccurrences.py : Not pythonic style. use 'count()' list method instead
- Perfect Job with the rest.

### session2
- 01_Python/03_Advanced/task2/InstallExtensions.py : Redundant code , use looping. 

### session3
- Perfect Job

### session4
- Perfect Job

Great Effort, Keep it up.

**Comment by RafikEmad** [comment]
Issues Resolved 
https://github.com/RafikEmad/EmbeddedLinux/commit/7f8c82a0098a24399b817232e20198c882a68da9
